:buffer_dialog			Create a buffer
:top_label			
Create a buffer around a geometry of the source. If the source is a collection then you can pick the geometry involved. If the source is a geometry then the buffer simply applies to this geometry. The shape of the buffer can be controlled in great detail. A buffer is usually used to find objects nearby the source collection.
:source_collection		Source
:geometry			Geometry
:distance			Distance [m]
:corner_style			Corner style
:end_style			End style
:geometry_collection		Source is a geometry
