:distance_filter_dialog		Filter on distance
:top_label			
Create a filter based on the distance from a geometry of the source. Only the records from the source collection that have a maximal distance to the geometry will be be yielded.
Except when inverse? is true, then the object further away will be yielded.
:source_collection		Source
:geometry			Geometry
:distance			Distance [m]
:target				Target
:inverse?			Inverse?
