:sw_view_eq_dialog		Create a view based on field equality
:top_label		Create a view between two collections based on a field with idential values in both collections. Typically this is a so-called foreign key. Select in both collections the field that should have the same value and then click Link set the relation. The equation is display above the right list.
Tick the fields that should be part of the result collection, they will be added to the right collection.
:swap	 	     	    Swap
:table_link		    Relation
:no_relation		    No relation. Click Link to set it
