:error_inserting		There was an error when inserting #1 (#2)
:dropping_table		      	Dropping the table #1
:creating_enums			Building new enumerators
:creating_table			Creating the table #1
:adding_index			Adding the index #1
:adding_geometry_fields		Adding geomety fields to the collection
:start_filling_the_collection  	Start copying the collection
:filling_the_collection	       	Copied so far: #1
:end_filling_the_collection    	Finished copying #1 records with #2 errors
:no_geom			No geometry found for '#1', so record is skipped
:spatial_export			Exporting a Spatial or Area collection. No alpha attributes.
