:link	 	     	Link
:no_table_yet		click Link to add a collection
:table_name		Collection
:use?			?
:img			
:source_field		Field
:linked_field		Field
:target_field		New Name
:table_name_invalid	The collection name '#1' is not valid for Smallworld. It should not contain "special" characters.
:please_enter_table_name    Please enter a target collection name first.
:table_name_exists	The collection name '#1' already exists. Please use another one.
:please_add_result_fields   Please add fields in the right list. Tick boxes in the left and middle list.
:no_double_names	    Names must be unique. '#1' is double.
:field_name_invalid	    The fieldname '#1' is not valid for Smallworld. It should not contain "special" characters.
