:binary_op_dialog		Create an collection combination
:top_label			Combine the records of the two collections based on the selected operator.
Intersection: return only the records that occur in both collections
Union: return the records from both collections. Doubles will be filtered.
X-Or: return the records that are exclusive in either collection.
Substraction: return the records from the source collection that are not in the filter collection.
:operation			Operation
:target				Target
:intersection			Intersection
:union				Union
:xor				X-Or
:subtraction			Substraction
