:colour				Colour...
:edit				Edit...
:new_file_title			Enter a new name for the Analysis dataset
:move_up			Up
:move_down			Down
:add_collections		Collections
:add_trail			Trail
:add_geom_selection		selected Map Geometry
:add_collection_selection	selected Map Collection
:add_explorer_content		Explorer
:add_explorer_selection		Explorer selection
:add_scrapbook			Scrapbook
:spatial_filter			Spatial
:distance_filter		Distance
:predicate_filter		Predicate
:follow_topology		Topology
:follow_join			Join
:follow_method			Customer Function
:follow_root			Root records
:create_spatial			Create Spatial collection
:create_buffer			Create Buffer
:intersection			Intersection
:union				Union
:subtraction			Subtraction
:xor				Xor
:view				Join 2 tables
:view_by_join			Join 2 tables by join
:view_by_eq			Join 2 tables equals fields
:materialize			Materialize collection
:materialize_spatial		Materialize spatial
:yes				Yes
:no				No
:sure_to_delete_workspace	Are you sure you want to delete the workarea '#1'?
:materializing			Materializing: #1
:sure_to_delete			Are you sure you want to delete #1 collections from the workspace?
:please_select_a_collection_and_geometry     Please select a record collection and a geometry or area.
:multiple_selection			     #1 selected collections
:no_bounds_to_goto		Sorry, there is no geometry to go to.
:provide_closed_trail		       Please provide a trail
:adding_from_explorer		       Adding elements from Explorer to the workspace...
:adding_selection_from_explorer	       Adding selected elements from Explorer to the workspace...
:adding_from_scrapbook		       Adding elements from the scrapbook
:scrapbook_is_empty		       The Scrapbook is empty
:set_operator_must_have_same_base      Set operators only work when the base collections are identical. Please select two collections with the same root base collection.
:view_only_possible_on_sw_collection   You can only create a view directly on an actual collection.
