:colour				Colour...
:edit				Edit...
:new_file_title			Enter a new name for the Analysis dataset
:move_up			Up
:move_down			Down

:add_collections		Collections
:add_collections_tooltip	Open a dialog to pick collections to add to the workspace

:add_trail			Trail
:add_trail_tooltip		Add the trail to the workspace

:add_geom_selection		selected Map Geometry
:add_geom_selection_tooltip	Add the selection in the main map to the workspace

:add_collection_selection	    	selected Map Collection
:add_collection_selection_tooltip	Add the collections that are selected in the main map to the workspace. Note: the collections are added, not the elements

:add_explorer_content		Explorer
:add_explorer_content_tooltip	Add the visible contents of the explorer to the workspace

:add_explorer_selection		Explorer selection
:add_explorer_selection_toltip	Add the selection in the explorer to the workspace

:add_scrapbook			Scrapbook
:add_scrapbook_tooltip		Add the contents of the scrapbook to the workspace

:spatial_filter			Spatial
:spatial_filter_tooltip		Filter the record collection on a spatial relation (eg inside) with a geometry

:distance_filter		Distance
:distance_filter_tooltip	Filter the records that are either with or outside a distance from a geometry

:predicate_filter		Predicate
:predicate_filter_tooltip	Filter a record collection based on a (complex) predicate

:follow_topology		Topology
:follow_topology_tooltip	Create a new record collection that is topological connected to the selected record collection

:follow_trace			Trace
:follow_trace_tooltip		Create a new record collection that is the result of a trace-out of selected record collection

:follow_join			Join
:follow_join_tooltip		Create a new record collection that is joined to the the selected record collection

:follow_method			Custom Function
:follow_method_tooltip		Create a new record collection based on custom software written for the selected record collection

:follow_root			Root records
:follow_root_tooltip		Create a new record collection based on one the root collections in the selected compound collection

:create_spatial			Create Spatial collection
:create_spatial_tooltip		Create a spatial collection for one of the geometries of the selected record collection

:create_buffer			Create Buffer
:create_buffer_tooltip		Create an area collection in the shape of a buffer around the selected collection

:intersection			Intersection
:intersection_tooltip		Create a new collection that is the intersection of the two selected collections

:union				Union
:union_tooltip			Create a new collection that is the union of the two selected collections

:subtraction			Subtraction
:subtraction_tooltip		Create a new collection that is the subtraction of the two selected collections

:xor				Xor
:xor_tooltip			Create a new collection that is the eXclusive OR of the two selected collections

:view				Join 2 tables
:view_by_join			Join 2 tables by join
:view_by_join_tooltip		Create a new record collection that the result of joining two tables by a join

:view_by_eq			Join 2 tables equals fields
:view_by_eq_tooltip		Create a new record collection that the result of joining two tables by matching fields

:materialize			Materialize collection
:materialize_tooltip		Create a new collection that is a materialised copy of the selected collection

:materialize_spatial		Materialize spatial
:materialize_spatial_tooltip	Create a new spatial collection that is a materialised copy of the selected collection

:yes				Yes
:no				No
:sure_to_delete_workspace	Are you sure you want to delete the workarea '#1'?
:materializing			Materializing: #1
:sure_to_delete			Are you sure you want to delete #1 collections from the workspace?
:please_select_a_collection_and_geometry     Please select a record collection and a geometry or area.
:multiple_selection			     #1 selected collections
:no_bounds_to_goto		Sorry, there is no geometry to go to.
:provide_closed_trail		       Please provide a trail
:adding_from_explorer		       Adding elements from Explorer to the workspace...
:adding_selection_from_explorer	       Adding selected elements from Explorer to the workspace...
:adding_from_scrapbook		       Adding elements from the scrapbook
:scrapbook_is_empty		       The Scrapbook is empty
:set_operator_must_have_same_base      Set operators only work when the base collections are identical. Please select two collections with the same root base collection.
:view_only_possible_on_sw_collection   You can only create a view directly on an actual collection.
:sorry_no_explorer		       Sorry, but we could not find the explorer in the application.
:closed_trail_col_name		       Closed Trail
:trail_col_name			       Trail Geometry
:copy_holder			       Copy of #1
:cannot_delete			       The collection #1 can not be deleted because it is used by #2 collections.
