:framework		Analysis Framework
:title			Analysis Framework: #2 in #1
:dirty_title		** Analysis Framework: #2 in #1
:title_for_empty_dialog	Analysis Framework. Please first open file
:file			File
:file_m			F
:exit			Exit
:exit_m			E
:edit			Edit
:edit_m			E
:workarea		Workarea
:workarea_m		W
:add_spatial		Add
:add_spatial_m		A
:filter			Filter
:filter_m		F
:collection		Filter
:follow			Follow
:follow_m		o
:spatial		Spatial
:spatial_m		S
:set			Set
:set_m			e
:materialize		Materialize
:materialize_m		M
:col			Collection
:col_m			C
