:materialize_dialog			Materialize
:top_label				Materialize the source collection for fast subsequent access. Any underlying analysis is performed once now and the resulting records are copied to the analysis dataset.
:new_table_name				New Tablename
:use?					Use?
:img					Img
:source_field				Source Field
:type					Type
:size					Size
:target_field				Target Field
:join_aspect				Join Aspect
:can_not_disable_key			You can not disable the key field #1. It is neccessary for the materialisation.
:table_name_exists			The table named #1 already exists. Pick an unique name.
