:predicate_filter_dialog		Set a predicate
:top_label				Create a predicate for the source collection to limit the number of records in the collection. Predicates that make use of attributes that are part of an index usually are fast.
:source_collection			Source
:indexes				Indexes
:no_indexes				No indexes available
:indexes_balloon			All indexes, just for information
:please_supply_a_predicate		Please supply a predicate
