:report_grouping_and_calculation_dialog		Report results
:top_label					Report on data in the source collection. You can group data and perform calculations on the group. Press the plus sign to add more lines. Note that the order of the lines is important: If you add a group on "Type" and put a sum on "Length" below it, then the sum of lengths will be grouped on type. If you put the sum of "Length" at the top then the sum of all lengths of all elements is reported.
:group						Group
:min						Min
:max						Max
:sum						Sum
:count						Count
:average					Average
:operator					Operator
:field						Field
:records					All records
:run						Run
:enter_valid_operator_at			Enter a valid operator (Group, Min, Max, etc) at line #1
:enter_a_field_name_at				Enter a field name at line #1
:reporting					Running a report on #1
