:export_to_excel		       Exporting to excel...
:export_to_access		       Exporting to Access...
:explorer			Explorer...
:goto				Goto
:goto_one			Goto one object
:no_bounds_to_goto		The collection has no bounding box to goto. Either the collection is empty or the elements in the collection have no geometry.
:highlight			Highlight
:highlighting			Highlighting the data
:going_to			Going to: #1
:sending_to_explorer		Sending collection to explorer
:calc				Report in groups and sums

:explorer_tooltip		Show the selected collection in the Analysis explorer
:goto_tooltip			Go to the bounds of the complete ocllection. Note: can be slow for complex collections
:goto_one_tooltip		Go to one of the records in the collection
:refresh_map_tooltip		Refresh the main map
:excel_tooltip			Show the selected collection in Excel
:access_tooltip			Show the selected collection in Access
:calc_tooltip			Open the Report dialog to construct a calculation report on the selected collection

