:shape_export_dialog	Create a Shapefile
:top_label		Create a Shapefile from the selection. Pick the geometry and the attributes to export and provide the filename. Also provide the scale factor. If the unit in Smallworld is [mm] and you require the export to be in [m], enter 0.001.
:source_collection	Source
:geometry		Geometry
:file_name		File:
:open_file_title	Open a Shapefile
:use?			Use?
:img			img
:source_field		Name
:result_field		Name
:result_length		Length
:result_type		Type
:table_name		Table
:scale			Scale
:provide_valid_scale	Provide a valid number (like 0.001) instead of '#1'
:invalid_geom_name	Invalid geomety name '#1'
:no_double_names	The field names should be unique, '#1' is not
