:shape_import_dialog	Open a Shapefile
:top_label		Open a Shape file and import it in the Analysis dataset. Provide the scale factor to apply to the geometry, if the unit in Smallworld is [mm] and the unit in the Shapefile is [m] enter 1000.
Note: this is an import function, so any changes to the shapefile after the import are not available in the dataset. 
:file_name		File:
:open_file_title	Open a Shapefile
:use?			Use?
:img			img
:shape_field		Name
:shape_length		Length
:shape_type		Type
:target_field		new Name
:table_name		Table
:scale			Scale
:no_double_names	The field names should be unique, '#1' is not
