:spatial_filter_dialog		Create a spatial relation
:top_label			define how a geometry of the source collection interacts with the target.
:source_holder			Source
:geometry			Geometry
:operation			Operation
:target				Target
:interacting_with		Any interaction
:touching			Touching
:dividing			Dividing
:overlaying			Overlaying
:overlapping			Overlapping
:within				Within
:equal_to			Equal to
:containing			Containing
:disjoint_from			Disjoint
