:spatial_filter_dialog		Create a spatial relation
:top_label			Define how a geometry of the source collection interacts with the geometry of the filter collection.#nIf you want to filter on the current trail or current selection, first copy the trail or selection to the workspace so it will show up in the filter dropdown.
:operation			Operation
:target				Target
:interacting_with		Any interaction
:touching			Touching
:dividing			Dividing
:overlaying			Overlaying
:overlapping			Overlapping
:within				Within
:equal_to			Equal to
:containing			Containing
:disjoint_from			Disjoint
