:trace_dialog		Trace topology
:top_label 			Trace the topological connection of a geometry of the source to find the target object. You can set stop predicates or give a maximum length.
:source_collection    		Source
:max_length			Max Length
:geometry			Geometry
:topology			Topology
:no_topology			No Topology
:build_predicate		Build Predicate
:edit_predicate			Edit
:remove_predicate		Delete
:remove_predicates		Delete All
:predicate_dialog_title		Build and set a predicate
