:trace_dialog		Trace topology
:top_label 			Trace the topological connection of a geometry of the source to find the target object. You can set stop predicates or give a maximum length.
:source_collection    		Source
:max_length			Max Length
:geometry			Geometry
:topology			Topology
:no_topology			No Topology
:build_predicate		Build Predicate
:edit_predicate			Edit
:remove_predicate		Delete
:remove_predicates		Delete All
:predicate_dialog_title		Build and set a predicate
:stop_predicates		Stop Predicates:
:add_predicate_tt		Open a dialog to construct a new stop predicate
:edit_predicate_tt		Open a dialog to edit the selected stop predicate
:remove_predicate_tt		Remove the selected stop predicate
:where				where 
